### ISSUE TITLE
能问问是什么问题呢 本地跑不动

### ISSUE THREAD

**Issue by wei-jun7** [liyupi/sql-mother#17]
failed to load config from C:\Users\LiWeiJun\Desktop\sql-mother-master\vite.config.ts
error when starting dev server:
Error:
You installed esbuild for another platform than the one you're currently using.
This won't work because esbuild is written with native code and needs to
install a platform-specific binary executable.

Specifically the "esbuild-windows-64" package is present but this platform
needs the "esbuild-windows-32" package instead. People often get into this
situation by installing esbuild on Windows or macOS and copying "node_modules"
into a Docker image that runs Linux, or by copying "node_modules" between
Windows and WSL environments.

If you are installing with npm, you can try not copying the "node_modules"
directory when you copy the files over, and running "npm ci" or "npm install"
on the destination platform after the copy. Or you could consider using yarn
instead of npm which has built-in support for installing a package on multiple
platforms simultaneously.

If you are installing with yarn, you can try listing both this platform and the
other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
Keep in mind that this means multiple copies of esbuild will be present.

Another alternative is to use the "esbuild-wasm" package instead, which works
the same way on all platforms. But it comes with a heavy performance cost and
can sometimes be 10x slower than the "esbuild" package, so you may also not
want to do that.

    at generateBinPath (C:\Users\LiWeiJun\Desktop\sql-mother-master\node_modules\esbuild\lib\main.js:1808:17)
    at esbuildCommandAndArgs (C:\Users\LiWeiJun\Desktop\sql-mother-master\node_modules\esbuild\lib\main.js:1886:33)
    at ensureServiceIsRunning (C:\Users\LiWeiJun\Desktop\sql-mother-master\node_modules\esbuild\lib\main.js:2051:25)
    at build (C:\Users\LiWeiJun\Desktop\sql-mother-master\node_modules\esbuild\lib\main.js:1942:26)
    at bundleConfigFile (file:///C:/Users/LiWeiJun/Desktop/sql-mother-master/node_modules/vite/dist/node/chunks/dep-2faf2534.js:63043:26)
    at loadConfigFromFile (file:///C:/Users/LiWeiJun/Desktop/sql-mother-master/node_modules/vite/dist/node/chunks/dep-2faf2534.js:63019:31)
    at resolveConfig (file:///C:/Users/LiWeiJun/Desktop/sql-mother-master/node_modules/vite/dist/node/chunks/dep-2faf2534.js:62643:34)
    at createServer (file:///C:/Users/LiWeiJun/Desktop/sql-mother-master/node_modules/vite/dist/node/chunks/dep-2faf2534.js:61943:26)
    at CAC.<anonymous> (file:///C:/Users/LiWeiJun/Desktop/sql-mother-master/node_modules/vite/dist/node/cli.js:707:30)

**Comment by wei-jun7** [comment]
up to date, audited 463 packages in 4s

84 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (5 moderate, 3 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by wei-jun7** [comment]
这个怎么修啊

**Comment by cq2021-coder** [comment]
> up to date, audited 463 packages in 4s
> 
> 84 packages are looking for funding
>   run `npm fund` for details
> 
> 9 vulnerabilities (5 moderate, 3 high, 1 critical)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force
> 
> Run `npm audit` for details.

这个不是已经告诉你解决方案了吗，运行npm audit fix或者npm audit fix --force

**Comment by wei-jun7** [comment]
跑完npm audit fix -- force 还是一样的，就是还是这个样子（就是第一个错误消息）。是那个esbuild-windows-32这个问题麻

**Comment by wei-jun7** [comment]
不是npm install 之后直接跑npm dev run 吗

**Comment by wei-jun7** [comment]
不是跑npm run dev 这个指令在npm install

**Comment by wei-jun7** [comment]
不是跑npm run dev 这个指令在npm install 之后

**Comment by wei-jun7** [comment]
VITE v3.2.7  ready in 477 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
出现了这个要怎么搞呢

**Comment by wei-jun7** [comment]
OK了 应该是我把 那个node.exe 放进了文件夹 然后他不知道执行哪一个
